apiVersion: apps/v1
kind: Deployment
metadata:
  name: smo-task12-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: smo-task12-server

  template:
    metadata:
      labels:
        app: smo-task12-server

    spec:
      containers:
        - name: server
          image: smo-task12-server:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080